import json
import re
import logging
from openai import OpenAI
import config

try:
    from vllm import LLM, SamplingParams
except ImportError:
    LLM = None
    SamplingParams = None

logger = logging.getLogger(__name__)

class PseudoCodeEvaluator:
    def __init__(self):
        self.mode = config.EVAL_MODE
        self.model_name = config.EVAL_MODEL

        if self.mode == "local":
            if LLM is None:
                raise ImportError("vLLM is required for local mode. Please install vllm.")
            logger.info(f"⚖️ Loading Evaluator Local Model: {self.model_name}...")
            self.llm = LLM(
                model=self.model_name,
                gpu_memory_utilization=config.EVAL_GPU_MEM,
                max_model_len=config.EVAL_MAX_MODEL_LEN,
                trust_remote_code=True
            )
            self.sampling_params = SamplingParams(
                temperature=0.0, # Deterministic output for evaluation
                max_tokens=config.EVAL_MAX_MODEL_LEN 
            )
        else:
            self.client = OpenAI(api_key=config.EVAL_API_KEY, base_url=config.EVAL_BASE_URL)

    def _extract_json_from_text(self, text: str) -> dict:
        """Safely extract JSON from raw text generated by a local LLM."""
        try:
            return json.loads(text)
        except json.JSONDecodeError:
            # Fallback: try to extract JSON block from markdown
            match = re.search(r'```json\s*(.*?)\s*```', text, re.DOTALL)
            if match:
                try:
                    return json.loads(match.group(1))
                except json.JSONDecodeError:
                    pass
            logger.warning(f"Failed to parse JSON from Evaluator output:\n{text}")
            return {}

    def _run_evaluation(self, prompt: str, is_alignment: bool) -> dict:
        """Unified interface for both local and API evaluation."""
        if self.mode == "local":
            # Force JSON output via prompt engineering for local models
            full_prompt = prompt + "\n\n⚠️ IMPORTANT: You MUST return ONLY valid JSON."
            outputs = self.llm.generate([full_prompt], self.sampling_params, use_tqdm=False)
            generated_text = outputs[0].outputs[0].text.strip()
            result = self._extract_json_from_text(generated_text)
            
            # Fallback for parsing failures
            if not result:
                if is_alignment:
                    return {"is_aligned": False, "issues": "Failed to parse JSON evaluation."}
                else:
                    return {"scores": {}, "feedback": "JSON parse error", "all_passed": False}
            return result
        else:
            try:
                response = self.client.chat.completions.create(
                    model=self.model_name,
                    messages=[{"role": "user", "content": prompt}],
                    response_format={"type": "json_object"}, # Enforce JSON at API level
                    temperature=0.0 if is_alignment else 0.1,
                    max_tokens=config.EVAL_MAX_TOKENS
                )
                return json.loads(response.choices[0].message.content)
            except Exception as e:
                logger.error(f"API Evaluator failed: {e}")
                if is_alignment:
                    return {"is_aligned": False, "issues": f"Evaluator Error: {e}"}
                else:
                    return {"scores": {}, "feedback": "Error", "all_passed": False}

    def verify_alignment(self, docstring: str, original_code: str, pseudo_code: str) -> dict:
        """Stage 1: Alignment Check (Gatekeeper)"""
        prompt = f"""
        You are a code logic verifier. Check if the "Generated Pseudo-code" aligns with the "Docstring" and "Original Code".
        
        [Docstring]: {docstring}
        [Original Code]: {original_code}
        [Pseudo-code]: {pseudo_code}
        
        Task:
        1. Semantic Consistency: Does the pseudo-code achieve the goal described in the docstring?
        2. Logical Equivalence: Does it follow the same control flow and handle the same edge cases as the original code?
        
        Output JSON only:
        {{
            "is_aligned": <bool>,
            "issues": "<concise description of logic/semantic mismatches, or 'None'>"
        }}
        """
        return self._run_evaluation(prompt, is_alignment=True)

    def evaluate_quality(self, docstring: str, original_code: str, pseudo_code: str) -> dict:
        """Stage 2: 5-Dimensional Quality Scoring"""
        prompt = f"""
        Evaluate the quality of the pseudo-code based on 5 dimensions (1-5 stars).
        
        [Docstring]: {docstring}
        [Original Code]: {original_code}
        [Pseudo-code]: {pseudo_code}

        ### Dimensions & Standards
        1. Correctness: Strict logic equivalence.
        2. Readability: Clear indentation, natural language.
        3. Completeness: Covers all steps and edge cases.
        4. Conciseness: High abstraction.
        5. Maintainability: Clear modular structure.

        Output JSON only:
        {{
            "scores": {{"correctness": <int>, "readability": <int>, "completeness": <int>, "conciseness": <int>, "maintainability": <int>}},
            "feedback": "<Advice>",
            "all_passed": <bool, true only if ALL scores >= 4>
        }}
        """
        return self._run_evaluation(prompt, is_alignment=False)